logging:
  level:
    root: info
  file:
    path: ./logs

spring:
  redis:
    cluster:
      nodes: 192.168.199.165:6391,192.168.199.165:6392,192.168.199.165:6393,192.168.199.165:6394,192.168.199.165:6395,192.168.199.165:6396
      max-redirects: 3
    lettuce:
      pool:
        max-active: 32
        min-idle: 8
        max-wait: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhw-free?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456


